version: 2.0.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2019
configuration: Release
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: dotnet test ./src/NetCoreForce.Client.Tests/NetCoreForce.Client.Tests.csproj